def monkeyKingMadLib():
    print("Monkey King Mad Lib")
    blank1 = raw_input("> Give me a verb: ")
    blank2 = raw_input("> Give me some plural for body parts: ")
    blank3 = raw_input("> Give me some sense of the body: ")
    blank4 = raw_input("> Give me a paste tense verb: ")
    blank5 = raw_input("> Give me the name of a fruit: ")
    blank6 = raw_input("> Give me an amount of time: ")
    blank7 = raw_input("> Give me a sort of push force, in its past tense: ")
    blank8 = raw_input("> Give me the name of a teacher: ")
    blank9 = raw_input("> Give me some athletic equipment: ")
    blank10 = raw_input("> Give me a noun: ")
    blank11 = raw_input("> Give me an adjective: ")
    blank12 = raw_input("> Give me an adverb: ")

    print("The day I saw the Monkey King %r. It was one of the most interesting days of the year. I cannot believe my %r. I had the %r running through my body for over a week." % (blank1, blank2, blank3))

    print("The Monkey King %r one of the largest %r I had seen in %r. The funniest thing was when he %r %r in a huge pile of %r" % (blank4, blank5, blank6, blank7, blank8, blank9))

    print("After he did that, the king played chess on his brother's %r and then combed his %r hair with a comb made out of old fish bones." % (blank10, blank11))

    print("Later, that same day, I saw the Monkey King dance %r in front of an audience of kangaroos and wombats." % (blank12))
monkeyKingMadLib()

def bikeRidingMadLib():
    print("Bike Riding Mad Lib")
    blank1 = raw_input("Give me a verb that ends in ing: ")
    blank2 = raw_input("Give me an adjective: ")
    blank3 = raw_input("Give me a verb that ends in ing: ")
    blank4 = raw_input("Give me a part of the body: ")
    blank5 = raw_input("Give me an adverb: ")
    blank6 = raw_input("Give me a part of the body: ")
    blank7 = raw_input("Give me a plural noun: ")
    blank8 = raw_input("Give me a verb: ")
    blank9 = raw_input("Give me a plural noun for an animal (flamingos): ")
    blank10 = raw_input("Give me a noun: ")
    blank11 = raw_input("Give me a verb: ")
    blank12 = raw_input("Give me an adjective: ")
    blank13 = raw_input("Give me a color: ")
    print("%r is a/an %r form of exercise." % (blank1, blank2))
    print("%r a bicycle enables you to develop your %r muscles as well as %r" % (blank3, blank4, blank5))
    print(" increase the rate of your %r beat. More %r" % (blank6, blank7))
    print(" around the world %r bicycles than drive %r. No matter what kind of %r" % (blank8, blank9, blank10))
    print(" you %r, always be sure to wear a/an %r helmet. Make sure to have %r reflectors too!" % (blank11, blank12, blank13))
bikeRidingMadLib()

def valentinesMadLib():
    print("Valentines Mad Lib")
    blank1=raw_input("Give me a noun: ")
    blank2=raw_input("Give me an ing verb: ")
    blank3=raw_input("Give me a noun: ")
    blank4=raw_input("Give me an adjective: ")
    blank5=raw_input("Give me a noun: ")
    blank6=raw_input("Give me a noun: ")
    blank7=raw_input("Give me an emotion: ")
    blank8=raw_input("Give me an action: ")
    blank9=raw_input("Give me a noun: ")
    blank10=raw_input("Give me a noun: ")
    blank11=raw_input("Give me the name of a friend: ")
    blank12=raw_input("Give me the name of the friend again: ")
    blank13=raw_input("Give me a noun: ")

    print("One Valentine's %r, I was %r when I looked in my %r " % (blank1, blank2, blank3))
    print("and saw a %r %r! It said, 'Will you be my %r?'"% (blank4, blank5, blank6))
    print("I was so %r! I %r to see who it was from , but there was no %r. " %(blank7, blank8, blank9))
    print("So, at %r, I asked for clues, but %r didn't know about it. Finally, someone told me that %r gave me the %r." %(blank10, blank11, blank12, blank13))
valentinesMadLib()

def excusedMadLib():
    print("Excused Mad Lib")

    blank1=raw_input("Give me a date: ")
    blank2=raw_input("Give me a name: ")
    blank3=raw_input("Give me an adjective: ")
    blank4=raw_input("Give me a noun: ")
    blank5=raw_input("Give me a name: ")

    print("Date: %r" % (blank1))
    print("Please excuse %r who is far too %r to attend %r class." % (blank2, blank3, blank4))
    print("Signed: %r" %(blank5))
excusedMadLib()

def sickExcuseMadLib():
    print("Sick Excuse MadLib")
    blank1=raw_input("Give me a date: ")
    blank2=raw_input("Give me a name: ")
    blank3=raw_input("Give me a part of the body: ")
    blank4=raw_input("Give me a type of liquid: ")
    blank5=raw_input("Give me a substance: ")
    blank6=raw_input("Give me a name: ")

    print("Date: %r" % (blank1))
    print("%r is sick with the %r flu. Drink more %r and take %r as needed." % (blank2, blank3, blank4, blank5))
    print("Signed: %r" % (blank6))
sickExcuseMadLib()

def hallPassMadLib():
    print("Hallpass Mad Lib")
    blank1=raw_input("Give me a date: ")
    blank2=raw_input("Give me a name: ")
    blank3=raw_input("Give me a place: ")
    blank4=raw_input("Give me a noun: ")
    blank5=raw_input("Give me a name: ")

    print("Date: %r" % (blank1))
    print("%r is authorized to be at %r instead of %r class." % (blank2, blank3, blank4))
    print("Signed: %r" % (blank5))
hallPassMadLib()

def coolHallPassMadLib():
    print("Cool Hallpass Mad Lib ")
    blank1=raw_input("Give me a date: ")
    blank2=raw_input("Give me a name: ")
    blank3=raw_input("Give me a noun: ")
    blank4=raw_input("Give me an event: ")
    blank5=raw_input("Give me a name: ")

    print("Date: %r" % (blank1))
    print("%r is too cool for %r class. Instead, she/he will be attending the %r class." %(blank2, blank3, blank4))
    print("Signed: %r" % (blank5))
coolHallPassMadLib()

def FFWinterMadLib():
    print("Fun Facts about Winter Mad Lib")
    blank1=raw_input("Give me a number: ")
    blank2=raw_input("Give me an adjective: ")
    blank3=raw_input("Give me a noun: ")
    blank4=raw_input("Give me a noun: ")
    blank5=raw_input("Give me a noun: ")
    blank6=raw_input("Give me an adjective: ")
    blank7=raw_input("Give me a noun: ")
    blank8=raw_input("Give me an ing verb: ")
    blank9=raw_input("Give me an ing verb: ")
    blank10=raw_input("Give me an ing verb: ")
    blank11=raw_input("Give me a beverage: ")
    blank12=raw_input("Give me a food: ")

    print("Winter is one of %r seasons of the year. The other seasons are %r, %r, and %r." % (blank1, blank2, blank3, blank4))
    print("Winter is the time of year when the %r is furthest from earth. The weather tends to be %r in winter, with %r fall and cold temperatures." %(blank5, blank6, blank7))
    print("Some winter sports include %r, %r, and %r . Hot %r with %r on top is a popular winter drink." % (blank8, blank9, blank10, blank11, blank12))
FFWinterMadLib()

def LunchRoomMadLib():
    print("Lunch Room Mad Lib")

    blank1=raw_input("Give me a container: ")
    blank2=raw_input("Give me an adjective: ")
    blank3=raw_input("Give me an adjective: ")
    blank4=raw_input("Give me a noun: ")
    blank5=raw_input("Give me an animal: ")
    blank6=raw_input("Give me a vegetable: ")
    blank7=raw_input("Give me a vegetable: ")
    blank8=raw_input("Give me a color: ")
    blank9=raw_input("Give me an adjective: ")

    print("Make sure your unch %r is filled with nutritious %r food." % (blank1, blank2))
    print("Do not go to the %r food stand across the street from school." % (blank3))
    print("The hamburgers they serve are fried in %r and are made of %r meat." %(blank4, blank5))
    print("So take a sandwich made of %r or %r, it's much healthier! Drink %r milk instead of %r colas." % (blank6, blank7, blank8, blank9))
LunchRoomMadLib()

def ParkTripMadLib():
    print("Trip to the Park! Mad Lib")

    blank1=raw_input("Give me a person: ")
    blank2=raw_input("Give me an adjective: ")
    blank3=raw_input("Give me an adjective: ")
    blank4=raw_input("Give me a noun: ")
    blank5=raw_input("Give me an adjective: ")
    blank6=raw_input("Give me a noun: ")
    blank7=raw_input("Give me an adjective: ")
    blank8=raw_input("Give me an adjective: ")
    blank9=raw_input("Give me a verb: ")
    blank10=raw_input("Give me a verb: ")
    blank11=raw_input("Give me a person: ")
    blank12=raw_input("Give me a verb: ")
    blank13=raw_input("Give me an adjective: ")
    blank14=raw_input("Give me a verb: ")

    print("Yesterday, %r and I went to the park. On our way to the %r park, we saw a %r %r on a bike." % (blank1, blank2, blank3, blank4))
    print("We also saw big %r balloons tied to a %r." % (blank5, blank6))
    print("Once we got to the %r park, the sky turned %r. It started to %r and %r." % (blank7, blank8, blank9, blank10))
    print("%r and I %r all the way home. Tomorrow, we will go to the %r park again and hope it doesn't %r." % (blank11, blank12, blank13, blank14))
ParkTripMadLib()
